### ISSUE TITLE
API 2.0 Breaking Change: 

### ISSUE THREAD

**Issue by petems** [blom/barge#16]
Breaking changes in Action objects (March 20, 2015)

Date: February 20, 2015 Tagged In: API v2 Author Phillip Baker
All action objects, i.e. those returned by the /v2/actions, /v2/droplets/$ID/actions and /v2/images/$ID/actions endpoint now return a region_slug attribute, in addition to a region attribute. At 00:01 March 20, 2015 UTC, API v2 will start returning an embedded region object at the region attribute, not a slug.

https://developers.digitalocean.com/documentation/changelog/api-v2/actions-breaking-changes-upgrade-path/

**Comment by blom** [comment]
All good. :+1:
